-- Step 1.2 + 1.3
-- User-scoped schema and RLS for Yeah Buddy Tracker.
-- Fixed version: Create tables first, then drop old policies, then recreate policies.

begin;

-- ========================
-- 1. Create tables first (so DROP POLICY doesn't fail)
-- ========================

-- Mirror auth.users into public.users
create table if not exists public.users (
  id uuid primary key references auth.users (id) on delete cascade,
  email text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists users_email_unique_idx
  on public.users (email)
  where email is not null;

-- set_updated_at helper function
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Auto-create public.users row on auth.users insert
create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.users (id, email)
  values (new.id, new.email)
  on conflict (id) do update
  set email = excluded.email,
      updated_at = now();

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row
execute function public.handle_new_auth_user();

-- muscle_groups
create table if not exists public.muscle_groups (
  id text not null,
  user_id uuid not null references public.users (id) on delete cascade,
  name text not null,
  weekly_target_kg numeric(10,2) not null check (weekly_target_kg >= 0),
  accent_color text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, id)
);

drop trigger if exists muscle_groups_set_updated_at on public.muscle_groups;
create trigger muscle_groups_set_updated_at
before update on public.muscle_groups
for each row
execute function public.set_updated_at();

-- exercises
create table if not exists public.exercises (
  id text not null,
  user_id uuid not null references public.users (id) on delete cascade,
  name text not null,
  muscle_group_id text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, id),
  constraint exercises_muscle_group_fk
    foreign key (user_id, muscle_group_id)
    references public.muscle_groups (user_id, id)
    on delete cascade
);

drop trigger if exists exercises_set_updated_at on public.exercises;
create trigger exercises_set_updated_at
before update on public.exercises
for each row
execute function public.set_updated_at();

-- workouts
create table if not exists public.workouts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users (id) on delete cascade,
  date_iso timestamptz not null,
  muscle_group_id text not null,
  exercise_id text not null,
  sets jsonb not null,
  notes text,
  created_at_iso timestamptz not null,
  inserted_at timestamptz not null default now(),
  constraint workouts_muscle_group_fk
    foreign key (user_id, muscle_group_id)
    references public.muscle_groups (user_id, id)
    on delete restrict,
  constraint workouts_exercise_fk
    foreign key (user_id, exercise_id)
    references public.exercises (user_id, id)
    on delete restrict
);

create index if not exists workouts_user_date_idx on public.workouts (user_id, date_iso desc);
create index if not exists workouts_user_muscle_group_idx on public.workouts (user_id, muscle_group_id);
create index if not exists workouts_user_exercise_idx on public.workouts (user_id, exercise_id);

-- app_settings
create table if not exists public.app_settings (
  id text not null default 'settings',
  user_id uuid not null references public.users (id) on delete cascade,
  is_muted boolean not null default false,
  unit text not null default 'kg' check (unit in ('kg')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, id)
);

drop trigger if exists app_settings_set_updated_at on public.app_settings;
create trigger app_settings_set_updated_at
before update on public.app_settings
for each row
execute function public.set_updated_at();

-- milestone_events
create table if not exists public.milestone_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users (id) on delete cascade,
  week_key text not null,
  muscle_group_id text not null,
  achieved_at_iso timestamptz not null,
  created_at timestamptz not null default now(),
  constraint milestone_events_one_per_week unique (user_id, week_key, muscle_group_id),
  constraint milestone_events_muscle_group_fk
    foreign key (user_id, muscle_group_id)
    references public.muscle_groups (user_id, id)
    on delete restrict
);

create index if not exists milestone_events_user_week_idx
  on public.milestone_events (user_id, week_key);

-- ========================
-- 2. Enable RLS on all tables
-- ========================

alter table public.users enable row level security;
alter table public.muscle_groups enable row level security;
alter table public.exercises enable row level security;
alter table public.workouts enable row level security;
alter table public.app_settings enable row level security;
alter table public.milestone_events enable row level security;

-- ========================
-- 3. Drop any existing policies (now safe because tables exist)
-- ========================

do $$
begin
  -- users
  drop policy if exists "users_select_own" on public.users;
  drop policy if exists "users_insert_own" on public.users;
  drop policy if exists "users_update_own" on public.users;

  -- muscle_groups
  drop policy if exists "muscle_groups_select_own" on public.muscle_groups;
  drop policy if exists "muscle_groups_insert_own" on public.muscle_groups;
  drop policy if exists "muscle_groups_update_own" on public.muscle_groups;
  drop policy if exists "muscle_groups_delete_own" on public.muscle_groups;

  -- exercises
  drop policy if exists "exercises_select_own" on public.exercises;
  drop policy if exists "exercises_insert_own" on public.exercises;
  drop policy if exists "exercises_update_own" on public.exercises;
  drop policy if exists "exercises_delete_own" on public.exercises;

  -- workouts
  drop policy if exists "workouts_select_own" on public.workouts;
  drop policy if exists "workouts_insert_own" on public.workouts;
  drop policy if exists "workouts_update_own" on public.workouts;
  drop policy if exists "workouts_delete_own" on public.workouts;

  -- app_settings
  drop policy if exists "app_settings_select_own" on public.app_settings;
  drop policy if exists "app_settings_insert_own" on public.app_settings;
  drop policy if exists "app_settings_update_own" on public.app_settings;
  drop policy if exists "app_settings_delete_own" on public.app_settings;

  -- milestone_events
  drop policy if exists "milestone_events_select_own" on public.milestone_events;
  drop policy if exists "milestone_events_insert_own" on public.milestone_events;
  drop policy if exists "milestone_events_update_own" on public.milestone_events;
  drop policy if exists "milestone_events_delete_own" on public.milestone_events;
end $$;

-- ========================
-- 4. Create fresh policies
-- ========================

-- public.users policies
create policy "users_select_own"
  on public.users for select to authenticated using (auth.uid() = id);

create policy "users_insert_own"
  on public.users for insert to authenticated with check (auth.uid() = id);

create policy "users_update_own"
  on public.users for update to authenticated 
  using (auth.uid() = id) with check (auth.uid() = id);

-- muscle_groups policies
create policy "muscle_groups_select_own"
  on public.muscle_groups for select to authenticated using (auth.uid() = user_id);

create policy "muscle_groups_insert_own"
  on public.muscle_groups for insert to authenticated with check (auth.uid() = user_id);

create policy "muscle_groups_update_own"
  on public.muscle_groups for update to authenticated 
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "muscle_groups_delete_own"
  on public.muscle_groups for delete to authenticated using (auth.uid() = user_id);

-- exercises policies
create policy "exercises_select_own"
  on public.exercises for select to authenticated using (auth.uid() = user_id);

create policy "exercises_insert_own"
  on public.exercises for insert to authenticated with check (auth.uid() = user_id);

create policy "exercises_update_own"
  on public.exercises for update to authenticated 
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "exercises_delete_own"
  on public.exercises for delete to authenticated using (auth.uid() = user_id);

-- workouts policies
create policy "workouts_select_own"
  on public.workouts for select to authenticated using (auth.uid() = user_id);

create policy "workouts_insert_own"
  on public.workouts for insert to authenticated with check (auth.uid() = user_id);

create policy "workouts_update_own"
  on public.workouts for update to authenticated 
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "workouts_delete_own"
  on public.workouts for delete to authenticated using (auth.uid() = user_id);

-- app_settings policies
create policy "app_settings_select_own"
  on public.app_settings for select to authenticated using (auth.uid() = user_id);

create policy "app_settings_insert_own"
  on public.app_settings for insert to authenticated with check (auth.uid() = user_id);

create policy "app_settings_update_own"
  on public.app_settings for update to authenticated 
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "app_settings_delete_own"
  on public.app_settings for delete to authenticated using (auth.uid() = user_id);

-- milestone_events policies
create policy "milestone_events_select_own"
  on public.milestone_events for select to authenticated using (auth.uid() = user_id);

create policy "milestone_events_insert_own"
  on public.milestone_events for insert to authenticated with check (auth.uid() = user_id);

create policy "milestone_events_update_own"
  on public.milestone_events for update to authenticated 
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "milestone_events_delete_own"
  on public.milestone_events for delete to authenticated using (auth.uid() = user_id);

commit;